# Generated by Django 2.2 on 2019-12-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
