# Generated by Django 2.2 on 2019-12-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
