# Generated by Django 2.2 on 2019-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='style',
            field=models.Field(),
        ),
    ]
