# Generated by Django 2.2 on 2019-12-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20191208_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
    ]
