# Generated by Django 2.2 on 2019-12-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_color'),
        ('forum', '0010_remove_post_style'),
    ]

    operations = [
    ]
